export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const RESET_PASSWORD_EMAIL_SENT= 'RESET_PASSWORD_EMAIL_SENT';
export const RESET_PASSWORD_SUCCEEDED = 'RESET_PASSWORD_SUCCEEDED';